### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by TheKnarf** [TheKnarf/RavenDesk#1]
The project needs a logo. The name of the project is inspired by the following quote from Alice's Adventures in Wonderland:

> Why is a raven like a writing desk?

I imagine the logo beeing in black and white, featuring a Raven sitting ontop of a writing desk with a pen in its mount trying to write. The I'd like the name of the project "Raven Desk" to be to the right of the pictogram written in a cursive handwritten font.

If you do a google image search for "raven writing desk" the first row of images gives an example of somewhat what I'd like the logo to look like, or be inspired by.

**Comment by richardbmx** [comment]
@TheKnarf Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by TheKnarf** [comment]
@richardbmx Great! Looking forward to it!

**Comment by richardbmx** [comment]
@TheKnarf perfect I will start working on it

**Comment by richardbmx** [comment]
I present my proposal inspired by the raven as you have asked, I hope you like it if you want any change you just have to ask for it.

![logo102](https://user-images.githubusercontent.com/35604837/45305002-67664200-b4e7-11e8-8e58-609aab050f6b.png)

**Comment by TheKnarf** [comment]
@richardbmx This looks amazing! I love it!

**Comment by richardbmx** [comment]
@TheKnarf Perfect if you do not have any changes I can make a google folder with all the necessary files to use the logo

**Comment by TheKnarf** [comment]
@richardbmx I sent you a mail to the email stated on your profile. Feel free to share the google folder there.

I love the design, it looks clean and modern.
